### ISSUE TITLE
Dev center script fails with no profiles

### ISSUE THREAD

**Issue by steveworkman** [lacostej/iOSprovisioningprofiles#2]
Hi,
1. Thank you so much for this script, it's a lifesaver.
2. If I've got a license that I use exclusively for distribution, not development, I get an error when running the job.
   Stack trace:
   - ruby ./apple_dev_center.rb -C CONFIGLOCATION.config -u USERNAME -d -O adc/site.json
     ./apple_dev_center.rb:139:in `read_profiles': undefined method`text' for nil:NilClass (NoMethodError)
     from /Library/Ruby/Gems/1.8/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:239:in `each'
     from /Library/Ruby/Gems/1.8/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:238:in`upto'
     from /Library/Ruby/Gems/1.8/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:238:in `each'
     from ./apple_dev_center.rb:135:in`read_profiles'
     from ./apple_dev_center.rb:153:in `read_all_profiles'
     from ./apple_dev_center.rb:150:in`each'
     from ./apple_dev_center.rb:150:in `read_all_profiles'
     from ./apple_dev_center.rb:176:in`fetch_site_data'
     from ./apple_dev_center.rb:208:in `dumpSite'
     from ./apple_dev_center.rb:223:in`main'
     from ./apple_dev_center.rb:228
     Fetching devices
     Fetching development profiles
     Fetching distribution profiles
     Build step 'Execute shell' marked build as failure

Tracing it back it looks like it's just failing on an empty row. Can an extra check be added?

**Comment by lacostej** [comment]
I can.

Do you have a copy of the HTML that the site displays for that particular line so I can understand exactly why this empty line is there ? is it just the profile name that is empty ? or any cell in that line ?

**Comment by lacostej** [comment]
I pushed something that should solve your problem. Feel free to add some extra information if you think it is worth it.

**Comment by steveworkman** [comment]
Thanks for the fix. On closer inspection of the portal, there are provisioning profiles available, it just was finding an empty row (that isn't there visually). The script works perfectly :-)
