### ISSUE TITLE
Nil error on fetching certificates for enterprise profile

### ISSUE THREAD

**Issue by steveworkman** [lacostej/iOSprovisioningprofiles#3]
Hi,
I'm getting an error when downloading certificates using the latest script. Stack trace below:

./apple_dev_center.rb:185:in `read_certificates_distribution': undefined method`at_xpath' for nil:NilClass (NoMethodError)
    from /Library/Ruby/Gems/1.8/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:239:in `each'
    from /Library/Ruby/Gems/1.8/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:238:in`upto'
    from /Library/Ruby/Gems/1.8/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:238:in `each'
    from ./apple_dev_center.rb:183:in`read_certificates_distribution'
    from ./apple_dev_center.rb:230:in `read_all_certificates'
    from ./apple_dev_center.rb:253:in`fetch_site_data'
    from ./apple_dev_center.rb:295:in `dumpSite'
    from ./apple_dev_center.rb:310:in`main'
    from ./apple_dev_center.rb:31

**Comment by lacostej** [comment]
You probably don't have distribution certificates. I've sent a fix to work around it.

If you DO have distribution certificates, take contact and send me the relevant HTML :)

Thanks

**Comment by steveworkman** [comment]
Hi, I've still got the issue, now on a different line:

./apple_dev_center.rb:190:in `read_certificates_distribution': undefined method`at_xpath' for nil:NilClass (NoMethodError)
    from /Library/Ruby/Gems/1.8/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:239:in `each'
    from /Library/Ruby/Gems/1.8/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:238:in`upto'
    from /Library/Ruby/Gems/1.8/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:238:in `each'
    from ./apple_dev_center.rb:187:in`read_certificates_distribution'
    from ./apple_dev_center.rb:235:in `read_all_certificates'
    from ./apple_dev_center.rb:258:in`fetch_site_data'
    from ./apple_dev_center.rb:300:in `dumpSite'
    from ./apple_dev_center.rb:315:in`main'
    from ./apple_dev_center.rb:320

Can you message me with an e-mail address so I can send you the view source. I'd rather not put it on here sorry

**Comment by lacostej** [comment]
I made 2 commits, you tried with both right ? Tip is at
3afd1a741328ebbdb19f0d466567952451af20c1

If yes, send me the HTML to jerome.lacoste @ GMAIL

J

On Tue, Mar 13, 2012 at 11:56 AM, Steve Workman
reply@reply.github.com
wrote:

> Hi, I've still got the issue, now on a different line:
> 
> ./apple_dev_center.rb:190:in `read_certificates_distribution': undefined method`at_xpath' for nil:NilClass (NoMethodError)
>        from /Library/Ruby/Gems/1.8/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:239:in `each'
>        from /Library/Ruby/Gems/1.8/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:238:in`upto'
>        from /Library/Ruby/Gems/1.8/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:238:in `each'
>        from ./apple_dev_center.rb:187:in`read_certificates_distribution'
>        from ./apple_dev_center.rb:235:in `read_all_certificates'
>        from ./apple_dev_center.rb:258:in`fetch_site_data'
>        from ./apple_dev_center.rb:300:in `dumpSite'
>        from ./apple_dev_center.rb:315:in`main'
>        from ./apple_dev_center.rb:320
> 
> Can you message me with an e-mail address so I can send you the view source. I'd rather not put it on here sorry
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lacostej/iOSprovisioningprofiles/issues/3#issuecomment-4471034

## 

Jerome Lacoste, +47 40867729, We Want To Know
