### ISSUE TITLE
Error in mobileprovisioning find name

### ISSUE THREAD

**Issue by steveworkman** [lacostej/iOSprovisioningprofiles#5]
Hi Jerome,

Using the latest version of the mobileprovisioning.rb I'm getting an error when trying to find the Name of the profile. Output from Jenkins below
- ./mobileprovisioning.rb /Volumes/Jenkins/ProvisioningProfiles/Standard/06D09458-CFCC-4B1D-B7DB-777B5973B621.mobileprovision -d Name
  /Library/Ruby/Gems/1.8/gems/plist-3.1.0/lib/plist/parser.rb:66:in `exists?': can't convert nil into String (TypeError)
  from /Library/Ruby/Gems/1.8/gems/plist-3.1.0/lib/plist/parser.rb:66:in`initialize'
  from /Library/Ruby/Gems/1.8/gems/plist-3.1.0/lib/plist/parser.rb:28:in `new'
  from /Library/Ruby/Gems/1.8/gems/plist-3.1.0/lib/plist/parser.rb:28:in`parse_xml'
  from ./mobileprovisioning.rb:56:in `dumpProfile'
  from ./mobileprovisioning.rb:115:in`main'
  from ./mobileprovisioning.rb:121

**Comment by lacostej** [comment]
ouch.

Is the name present in the .mobileprovision file at all ?

J

On Thu, Jun 28, 2012 at 10:52 AM, Steve Workman
reply@reply.github.com
wrote:

> Hi Jerome,
> 
> Using the latest version of the mobileprovisioning.rb I'm getting an error when trying to find the Name of the profile. Output from Jenkins below
> - ./mobileprovisioning.rb /Volumes/Jenkins/ProvisioningProfiles/Standard/06D09458-CFCC-4B1D-B7DB-777B5973B621.mobileprovision -d Name
>   /Library/Ruby/Gems/1.8/gems/plist-3.1.0/lib/plist/parser.rb:66:in `exists?': can't convert nil into String (TypeError)
>          from /Library/Ruby/Gems/1.8/gems/plist-3.1.0/lib/plist/parser.rb:66:in`initialize'
>          from /Library/Ruby/Gems/1.8/gems/plist-3.1.0/lib/plist/parser.rb:28:in `new'
>          from /Library/Ruby/Gems/1.8/gems/plist-3.1.0/lib/plist/parser.rb:28:in`parse_xml'
>          from ./mobileprovisioning.rb:56:in `dumpProfile'
>          from ./mobileprovisioning.rb:115:in`main'
>          from ./mobileprovisioning.rb:121
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lacostej/iOSprovisioningprofiles/issues/5

## 

Jerome Lacoste, +47 40867729, We Want To Know

**Comment by steveworkman** [comment]
Err, no, it's downloaded it as a buffer rather than plain text

**Comment by steveworkman** [comment]
Hold on, scrap that, that's Sublime being silly. There is a name key in there, vim picks it up (lines 64&65 of the mobileprovisioning file)

**Comment by lacostej** [comment]
Fixed in 899687dc632c34b6b9e29d1b75250a5b5542fb7e

**Comment by steveworkman** [comment]
Awesome. This now works perfectly, thanks!
